apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ycn5o10ux-nodejs 
  janus-idp.io/tekton: ycn5o10ux-nodejs
  backstage.io/kubernetes-id: ycn5o10ux-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ycn5o10ux-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  